{
  lib,
  buildNpmPackage,
  fetchFromGitHub,
  fetchzip,
  versionCheckHook,
  writableTmpDirAsHomeHook,
  fd,
  ripgrep,
  makeBinaryWrapper,
  stdenvNoCC,
}:
buildNpmPackage (finalAttrs: {
  pname = "pi-coding-agent";
  version = "0.85.1";

  src = fetchFromGitHub {
    owner = "earendil-works";
    repo = "pi";
    tag = "v${finalAttrs.version}";
    hash = "sha256-gU8BSiqqOYt2RRuQONHHGvZeSM5KFQVrwif9bmuUXUc=";
  };

  npmDepsHash = "sha256-jzlsZIQzfl1FCZZ5//dHFWwMfBZQ4nRD6KB4HHifPqE=";

  # The provider model catalog (packages/ai/src/providers/data/) is generated by
  # a network fetch and gitignored upstream, so it is absent from the source
  # tarball. Restore it from the matching published @earendil-works/pi-ai npm
  # package, which ships the hydrated catalog under dist/providers/data/.
  modelData = fetchzip {
    url = "https://registry.npmjs.org/@earendil-works/pi-ai/-/pi-ai-${finalAttrs.version}.tgz";
    hash = "sha256-KzewhtP1DRFDIOrJ4wN9bKwG3EioQW7eTsipK5AJ2z8=";
  };

  patches = [
    ./normalize-package-display-paths.patch
  ];

  postPatch = ''
    cp -r ${finalAttrs.modelData}/dist/providers/data packages/ai/src/providers/
  '';

  npmWorkspace = "packages/coding-agent";

  # Skip native module rebuild for unneeded workspaces.
  npmRebuildFlags = ["--ignore-scripts"];

  nativeBuildInputs = [
    makeBinaryWrapper
  ];

  # Build workspace dependencies in order, then the CLI itself. tsgo is
  # invoked directly to skip pi-ai's generate-models script, which needs
  # network access; modelData supplies its output instead.
  buildPhase = ''
    runHook preBuild

    npm exec -- tsgo -p packages/telemetry/tsconfig.build.json
    npm exec -- tsgo -p packages/chord/tsconfig.build.json
    npm exec -- tsgo -p packages/tui/tsconfig.build.json
    npm exec -- tsgo -p packages/ai/tsconfig.build.json
    npm exec -- tsgo -p packages/protocol/tsconfig.build.json
    npm exec -- tsgo -p packages/agent/tsconfig.build.json
    npm exec -- tsgo -p packages/client/tsconfig.build.json
    npm exec -- tsgo -p packages/server/tsconfig.build.json
    npm run build --workspace=packages/coding-agent

    runHook postBuild
  '';

  # Prune the whole monorepo, not only the coding-agent workspace.
  dontNpmPrune = true;
  preInstall = ''
    npm prune --omit=dev --no-save
  '';

  # Replace runtime workspace symlinks with real copies.
  postInstall =
    ''
      local nm="$out/lib/node_modules/pi-monorepo/node_modules"
      local pkgRoot="$out/lib/node_modules/pi-monorepo"
      local shareRoot="$out/share/pi-coding-agent"

      for ws in @earendil-works/chord:packages/chord \
                @earendil-works/pi-ai:packages/ai \
                @earendil-works/pi-agent-core:packages/agent \
                @earendil-works/pi-tui:packages/tui \
                @earendil-works/pi-telemetry:packages/telemetry \
                @earendil-works/pi-protocol:packages/protocol \
                @earendil-works/pi-client:packages/client; do
        IFS=: read -r pkg src <<< "$ws"
        rm "$nm/$pkg"
        cp -r "$src" "$nm/$pkg"
      done

      find "$nm" -type l -lname '*/packages/*' -delete
      find "$nm/.bin" -xtype l -delete

      mkdir -p "$shareRoot"
      cp "$pkgRoot/package.json" "$shareRoot/"
      cp "$pkgRoot/README.md" "$shareRoot/"
      cp "$pkgRoot/CHANGELOG.md" "$shareRoot/"
      cp -r "$pkgRoot/docs" "$shareRoot/"
      cp -r "$pkgRoot/examples" "$shareRoot/"
      cp -r "$pkgRoot/dist" "$shareRoot/"
    ''
    + lib.optionalString stdenvNoCC.hostPlatform.isDarwin ''
      # Remove foreign Linux binaries that make audit-tmpdir try to inspect
      # ELF RPATHs with patchelf.
      rm -rf \
        "$nm/@anthropic-ai/sandbox-runtime/dist/vendor/seccomp" \
        "$nm/@anthropic-ai/sandbox-runtime/vendor/seccomp"
    '';

  postFixup = ''
    wrapProgram $out/bin/pi \
      --prefix PATH : ${lib.makeBinPath [fd ripgrep]} \
      --set-default PI_PACKAGE_DIR "$out/share/pi-coding-agent" \
      --set-default PI_SKIP_VERSION_CHECK 1 \
      --set-default PI_TELEMETRY 0
  '';

  doInstallCheck = true;
  nativeInstallCheckInputs = [
    writableTmpDirAsHomeHook
    versionCheckHook
  ];
  versionCheckKeepEnvironment = ["HOME"];
  versionCheckProgram = "${placeholder "out"}/bin/pi";
  versionCheckProgramArg = "--version";

  passthru.updateScript = ./update.sh;

  meta = {
    description = "Coding agent CLI with read, bash, edit, write tools and session management";
    homepage = "https://github.com/earendil-works/pi";
    downloadPage = "https://www.npmjs.com/package/@earendil-works/pi-coding-agent";
    changelog = "https://github.com/earendil-works/pi/blob/v${finalAttrs.version}/packages/coding-agent/CHANGELOG.md";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [];
    mainProgram = "pi";
  };
})
